#!/usr/bin/env bash

# Function to check if a string is an integer
is_integer() {
    [[ "$1" =~ ^[0-9]+$ ]]
}

# Function to validate day input
validate_day() {
    local day=$1
    if [ -z "$day" ]; then
        echo "Error: Day argument is required"
        exit 1
    fi

    if ! is_integer "$day"; then
        echo "Error: Day must be an integer"
        exit 1
    fi

    if (( day < 1 || day > 25 )); then
        echo "Error: Day must be between 1 and 25"
        exit 1
    fi
}

validate_year() {
    local year=$1
    if [ -z "$year" ]; then
        # That should not happen since we setup a default value to the current year
        echo "Error: Year argument is required and the default value is not defined"
        exit 1
    fi

    if ! is_integer "$year"; then
        echo "Error: Year must be an integer"
        exit 1
    fi
}

# Get the script directory
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# Validate day argument
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    echo "Usage: <day> [<year>]"
    exit 1
fi
day="$1"
validate_day "$day"
year="${2:-$(date +%Y)}"
validate_year "$year"

# Create paths
YEAR_PATH="$SCRIPT_DIR/libs/$year"
CODE_PATH="$YEAR_PATH/day$(printf '%02d' "$day")"

# Check if paths already exist
if [ -d "$CODE_PATH" ]; then
    echo "Error: Code directory already exists"
    exit 1
fi

# Create directories
mkdir -p "$CODE_PATH"

# Create templatesPath
TEMPLATES_PATH="$SCRIPT_DIR/data/templates"

# Find all .tmpl files
files=$(find "$TEMPLATES_PATH" -type f -name "*.tmpl")

# Copy .tmpl files to codePath
for file in $files; do
    # Extract filename without directory
    FILE_NAME=$(basename "$file" '.tmpl')

    # Copy the file to the new location
    cp "$file" "$CODE_PATH/$FILE_NAME"
done

# Create input and input_test files in dataPath
touch "$CODE_PATH/input"
touch "$CODE_PATH/input_test"

echo "Files created successfully in:"
echo "$CODE_PATH"
